### ISSUE TITLE
Add `is_free` param

### ISSUE THREAD

**Issue by willdurand** [clermontech/planet#54]
``` yaml

---
# Event title (optional)
title: "APIHour #6"

# When is it? (required)
event_date: "2013-12-17 19:00:00"

# Tell us more about your event! (optional, but... heavily recommended)
description:
    The description...
    can be written in multiline, and **Markdown** can be used.
    Please, do not add any images, only plain text with text decoration.

# Is this event free?
is_free: true|false

...
```

If the event is **not** free, a `$$$` icon should be displayed right after the title.
